//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityTax
    {
        public byte Id { get; set; }
        public byte MunicipalityId { get; set; }
        public byte TaxType { get; set; }
        public System.DateTime TaxDate { get; set; }
        public double Tax { get; set; }
    
        public virtual Municipality Municipality { get; set; }
        public virtual TaxType TaxType1 { get; set; }
    }
}
